twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: '%app.name%'
        app_description: '%app.description%'
        app_version: '%app.version%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
