twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: '%app_name%'
        app_description: '%app_description%'
        app_version: '%app_version%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
